### ISSUE TITLE
<user_name> placeholder fails

### ISSUE THREAD

**Issue by perlsol** [DarkBlade12/ItemSlotMachine#18]
in the slotmachines/1.yml
If you have more than 1 win action then the <user_name> placeholder fails...

```
  points:
    pattern: ['bell', 'bell', 'bell']
    actions:
      - 'EXECUTE_COMMAND:playerpoints:p give <user_name> 150'
      - 'EXECUTE_COMMAND:say <user_name> just won 150 points playing Fruit Frenzy'
```
      
FIX: Use <name>

```
  points:
    pattern: ['bell', 'bell', 'bell']
    actions:
      - 'EXECUTE_COMMAND:playerpoints:p give <user> 150'
      - 'EXECUTE_COMMAND:say <user> just won 150 points playing Fruit Frenzy'
```
